name: e_commerce
description: Premium E-Commerce App - Velora
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.11.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # ==========================
  # Localization
  # ==========================
  easy_localization: ^3.0.8

  cupertino_icons: ^1.0.8

  # ==========================
  # UI
  # ==========================
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  cached_network_image: ^3.4.1

  # ==========================
  # State Management
  # ==========================
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # ==========================
  # Dependency Injection
  # ==========================
  get_it: ^8.2.0

  # ==========================
  # Firebase
  # ==========================
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.4

  # ==========================
  # Networking
  # ==========================
  dio: ^5.9.0

  # ==========================
  # Functional Programming
  # ==========================

  # ==========================
  # Local Storage
  # ==========================
  shared_preferences: ^2.5.3

  # ==========================
  # Maps & Location
  # ==========================
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lottie/
    - assets/translations/