// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXoSvosGyDNGZRPD8_sQkwux52etiN1dk',
    appId: '1:187874809065:web:a4f623ce56a47ef4b78c78',
    messagingSenderId: '187874809065',
    projectId: 'velora-c2959',
    authDomain: 'velora-c2959.firebaseapp.com',
    storageBucket: 'velora-c2959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnZYeZc1YtJlmmAlnYKqbkXmtzjNEec8M',
    appId: '1:187874809065:android:43f39f8bb2486119b78c78',
    messagingSenderId: '187874809065',
    projectId: 'velora-c2959',
    storageBucket: 'velora-c2959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC521t3SBomhUozjPzenuD_ZKuR4AgqJOg',
    appId: '1:187874809065:ios:57984da1168eef48b78c78',
    messagingSenderId: '187874809065',
    projectId: 'velora-c2959',
    storageBucket: 'velora-c2959.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC521t3SBomhUozjPzenuD_ZKuR4AgqJOg',
    appId: '1:187874809065:ios:57984da1168eef48b78c78',
    messagingSenderId: '187874809065',
    projectId: 'velora-c2959',
    storageBucket: 'velora-c2959.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXoSvosGyDNGZRPD8_sQkwux52etiN1dk',
    appId: '1:187874809065:web:e2860af7c4b52376b78c78',
    messagingSenderId: '187874809065',
    projectId: 'velora-c2959',
    authDomain: 'velora-c2959.firebaseapp.com',
    storageBucket: 'velora-c2959.firebasestorage.app',
  );
}
